export const GAME_CONSTANTS = {
  WIDTH: 400,
  HEIGHT: 700,
  KAMA_MAX: 100,
  KAMA_INITIAL: 80,
  KAMA_DRAIN_PER_SEC: 15,
  KAMA_PER_TAP: 8,
  TAP_POWER: 260,
  GRAVITY: 320,
  SLIDE_SPEED: 180,
  KAMA_RECOVERY_ON_SLIDE: 35,
  GIFT_KAMA_BONUS: 25,
  STEP_HEIGHT: 120, // Khoảng cách pixel giữa các bậc
};
